---
name: "PHP Code Beautifier and Fixer"
description: Sniff the PHP code and beautify it if necessary.

author:
  name: "Stanislav Rejthar"
  email: "rejthar@stanislavrejthar.com"
  url: "https://github.com/WorkOfStan"

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  commit-changes:
    description: "If true, commit changes to the current branch"
    type: boolean
    default: false
  commit-message:
    description: "Commit message for the changes"
    type: string
    default: "PHP Code Beautifier fixes applied automatically"
  debug:
    description: "Enable extra debug output"
    type: boolean
    default: false
  # https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Advanced-Usage#specifying-valid-file-extensions
  # By default, PHP_CodeSniffer will check any file it finds with a .inc, .php, .js or .css extension, although not all standards will actually check all these file types.
  # Empty value means no checking at all.
  # The default is `php` as js and css are handled by prettier.
  # Btw: JS/CSS support will be removed from PHP_CodeSniffer in PHPCS 4.x. Source: https://phpcsutils.com/
  extensions:
    description: "Comma delimited list of extensions to be sniffed"
    required: false
    type: string
    default: "php" # "php,inc,lib"
  ignore:
    description: "Ignore files based on a comma-separated list of patterns matching files and/or directories."
    required: false
    type: string
    default: "vendor/"
  php-version:
    description: "PHP version to be used for running phpcs and phpcbf"
    required: false
    type: string
    default: "8.2"
  standard:
    description: "The name of, or the path to, the coding standard to use. Can be a comma-separated list specifying multiple standards."
    required: false
    type: string
    default: "" # if left empty, .github/linters/phpcs.xml or https://github.com/super-linter/super-linter/blob/main/TEMPLATES/phpcs.xml will be used
  stop-on-manual-fix:
    description: "If true, the execution will stop when manual fixes are necessary."
    type: boolean
    default: false

outputs:
  branch-name:
    description: "The branch where changes were committed"
  changed-files:
    description: "Comma-separated list of files changed by phpcbf"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }} # Fetch latest changes (even by previous job)
        fetch-depth: 0 # Fetch all history for all branches and tags. Otherwise github.event.pull_request.base.ref SHA isn't found.

    # Fetch latest changes (even by previous job)
    - name: Fetch latest changes
      run: git pull origin ${{ github.ref }}
      shell: bash

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ inputs.php-version }}"
        tools: composer:v2

    # https://github.com/actions/cache
    # A repository can have up to 10 GB of caches. Once the 10 GB limit is reached, older caches will be evicted based on when the cache was last accessed.
    # Caches that are not accessed within the last week will also be evicted.
    - name: Cache composer dependencies
      uses: actions/cache@v4
      id: vendor-cache
      with:
        # path to Checkout working directory is /home/runner/work/repo-name/repo-name , so just add /vendor/
        path: ${{ github.workspace }}/vendor/
        # Use composer.json for key, if composer.lock is not committed.
        key: phpcs-fix-${{ runner.os }}-PHP${{ inputs.php-version }}-vendor-${{ hashFiles('**/composer.json') }}

    - name: "Use the latest PHPCS version"
      if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
      run: composer require --dev squizlabs/php_codesniffer --prefer-dist --no-progress
      shell: bash

    - name: Debug branches
      if: ${{ inputs.debug == 'true' }}
      run: |
        echo "Debug 1. List All Local Branches"
        git branch
        echo "Debug 2. List All Remote Branches"
        git branch -r
        echo "Debug 3. List All References (Including Detached HEADs)"
        git show-ref
        echo "Debug 4. Check Your Current Checked-out Reference"
        git status
      shell: bash

    - name: Run PHP Code Sniffer
      id: phpcs
      run: |
        # Determine which coding standard to use.
        # Priority:
        #   1. Use inputs.standard if provided (non-empty).
        #   2. If not, use the repository's own phpcs.xml if available.
        #   3. Otherwise, fall back to the action's default template. Which is a copy of https://github.com/super-linter/super-linter/blob/main/TEMPLATES/phpcs.xml
        if [ -n "${{ inputs.standard }}" ]; then
          use_standard="${{ inputs.standard }}"
        elif [ -f .github/linters/phpcs.xml ]; then
          use_standard=".github/linters/phpcs.xml"
        else
          use_standard="$GITHUB_ACTION_PATH/.github/linters/super-linter-templates-phpcs.xml"
        fi
        echo "USE_STANDARD=$use_standard" >> "$GITHUB_ENV" # for subsequent steps
        echo "phpcs standard=$use_standard"
        vendor/bin/phpcs --extensions="${{ inputs.extensions }}" . --standard="$use_standard" --ignore="${{ inputs.ignore }}" || HAS_ISSUES=true
        # because of `||`, the previous command always exit 0

        # Default the variable if no issues were found
        : "${HAS_ISSUES:=false}"
        echo "HAS_ISSUES=$HAS_ISSUES" >> $GITHUB_ENV
      shell: bash

    - name: Run PHP Code Beautifier if needed
      id: fix
      if: env.HAS_ISSUES == 'true'
      run: |
        echo "phpcbf standard=${{ env.USE_STANDARD }}"
        PHPCBF_EXIT_CODE=0
        MORE_ISSUES=false
        vendor/bin/phpcbf --extensions="${{ inputs.extensions }}" . --standard="${{ env.USE_STANDARD }}" --ignore="${{ inputs.ignore }}" || PHPCBF_EXIT_CODE=$?
        if [ ${PHPCBF_EXIT_CODE} -ne 0 ]; then
          echo "::notice title=PHPCBF wasn't idle::Non-zero code exit of phpcbf = ${PHPCBF_EXIT_CODE} (phpcbf wasn't idle)"

          vendor/bin/phpcs --extensions="${{ inputs.extensions }}" . --standard="${{ env.USE_STANDARD }}" --ignore="${{ inputs.ignore }}" || MORE_ISSUES=true
          # because of `||`, the previous command always exit 0
          if [ "${MORE_ISSUES}" = "true" ]; then
            echo "::warning title=Some PHPCS issues remained.::Some phpcs issues remained. Manual fix necessary."
          fi
        fi

        # restore composer.json before staging the changes
        git checkout composer.json

        # Check for fixable changes
        if [ -z "$(git status --porcelain)" ]; then
          echo "::warning title=No fixable errors were found by PHPCBF::No fixable errors were found by phpcbf: Manual fix necessary. Compare to the PHP Code Sniffer section above."
          if [ "${{ inputs.stop-on-manual-fix }}" = "true" ]; then
            # Indicates an error
            # This sets the output named branch-name to an empty value. Which is useful to signal “no branch was created” in a way that downstream steps can detect reliably.
            echo "branch-name=" >> $GITHUB_OUTPUT
            echo "changed-files=" >> $GITHUB_OUTPUT
            exit 1
          else
            # Exiting gracefully
            echo "branch-name=" >> $GITHUB_OUTPUT
            echo "changed-files=" >> $GITHUB_OUTPUT
            exit 0
          fi
          # The rest of the script must still be within the same step to really stop the execution
        fi

        # Only add changed files, safe for spaces
        git status --porcelain | awk '{print $2}' | while IFS= read -r file; do git add "$file"; done

        # Determine branch name based on commit-changes input
        if [ "${{ inputs.commit-changes }}" == "true" ]; then
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
          if [ "$BRANCH_NAME" == "HEAD" ] || [ -z "$BRANCH_NAME" ]; then
            echo "Detached HEAD detected. Checking out the PR branch directly from origin..."
            # Fetch the PR branch tip and force a local branch matching the remote head
            # Note: ${{ github.head_ref }} is a GitHub Actions built-in variable that contains the name of the source branch of a pull request (PR).
            #   It is only available during workflow runs triggered by pull_request events.
            git fetch origin ${{ github.head_ref }} --depth=1
            git checkout -B "${{ github.head_ref }}" "origin/${{ github.head_ref }}"
            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          fi
          NOTICE_MESSAGE="A PHPCBF commit was successfully added to the current branch: $BRANCH_NAME"
        else
          # name includes timestamp and short_hash
          BRANCH_NAME="phpcbf/fix-$(date +'%y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
          git checkout -b "$BRANCH_NAME"
          echo "::warning title=New branch created::New branch created: Consider pull request for a new branch: $BRANCH_NAME (or delete it)"
          NOTICE_MESSAGE="A PHPCBF commit was successfully added to the new branch: $BRANCH_NAME"
        fi

        # Configure Git user
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Commit and push changes with custom message
        git commit -m "${{ inputs.commit-message }} on $(date +'%Y-%m-%d %H:%M:%S') UTC"
        git push origin "$BRANCH_NAME"
        echo "::notice title=PHPCBF commit added::${NOTICE_MESSAGE}"
        COMMIT_URL=${{ github.server_url }}/${{ github.repository }}/commit/$(git rev-parse HEAD)
        echo "::notice title=View the PHPCBF commit::${COMMIT_URL}"

        # Set outputs
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD | tr '\n' ',' | sed 's/,$//')
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "changed-files=${CHANGED_FILES}" >> $GITHUB_OUTPUT

        ## Stop with an error if some manual fixes are required on top of automatic fixes
        if [ "${{ inputs.stop-on-manual-fix }}" = "true" ] && [ "${MORE_ISSUES}" = "true" ]; then
          exit 1
        fi
      shell: bash

    - name: No changes output (when no fix needed)
      if: steps.fix.outcome == 'skipped'
      run: |
        echo "branch-name=" >> $GITHUB_OUTPUT
        echo "changed-files=" >> $GITHUB_OUTPUT
      shell: bash

    - name: Debug GITHUB_OUTPUT
      if: ${{ inputs.debug == 'true' }}
      run: |
        echo "— Contents of GITHUB_OUTPUT file —"
        cat "$GITHUB_OUTPUT"
      shell: bash
