---
name: Phpcs-fix

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

permissions:
  contents: write

jobs:
  phpcs-phpcbf:
    runs-on: ubuntu-latest
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Invoke the PHPCS check and PHPCBF fix
        # Use the latest commit in the main branch.
        uses: WorkOfStan/phpcs-fix@main
        with:
          commit-changes: true
          #debug: true
          stop-on-manual-fix: true
