---
name: Phpcs-fix
on: [pull_request, push]

permissions:
  contents: write

jobs:
  phpcs-phpcbf:
    runs-on: ubuntu-latest
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Invoke the PHPCS check and PHPCBF fix
        # Use the latest commit in the main branch.
        uses: WorkOfStan/phpcs-fix@main
        with:
          commit-changes: true
          stop-on-manual-fix: true
